export interface Paint {
    code: number;
    en_name: string;
    fr_name: string;
    jp_name: string;
    series: "A" | "B" | "C" | "D" | "E" | "F";
    perm: 0 | 1 | 2 | 3 | 4;
    opacity: 0 | 1 | 2 | 3;
    staining: 0 | 1 | 2;
    granulation: boolean;
    pigments: string[];
    size: [number, number, number]; // 5ml 15ml 60ml
    sets: [number, number, number, number, number, number, number, number];
}

export const paintFilters = [
    "Permanence",
    "Opacity",
    "Staining",
    "Granulating",
    "Series",
    "Family",
    "Sets",
    "Size",
];

export const paintSymbols = {
    opacity: ["◯", "⦶", "◐", "⬤"],
    staining: ["☐", "◩", "◼"],
};

export const paintFamily = {
    red: [
        5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 25, 26, 27,
    ],
    yellow: [
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48,
        49, 50, 51,
    ],
    green: [60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 74, 75, 77, 78, 79],
    blue: [
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 102, 103, 104, 105, 106,
        107, 108,
    ],
    violet: [110, 112, 113, 115, 116, 117, 119, 120, 170, 175],
    brown_black: [
        129, 130, 131, 132, 133, 134, 135, 136, 139, 141, 142, 137, 138, 140,
    ],
    grey_white: [151, 152, 153, 155, 156, 157, 2, 3],
    gold_silver: [190, 191],
};

export const hbPaints: Paint[] = [
    // RED
    {
        code: 5,
        en_name: "Quinacridone Red",
        fr_name: "Rouge Quinacridone",
        jp_name: "キナクリドン　レッド",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PV19"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 6,
        en_name: "Pyrrole Rubin",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 7,
        en_name: "Pyrrole Red",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 2,
        staining: 2,
        granulation: false,
        pigments: ["PR254"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 8,
        en_name: "Perylene Maroon",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PR179"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 9,
        en_name: "Permanent Alizarin Crimson",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PV19", "PBr25"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 10,
        en_name: "Crimson Lake",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR177", "PR122", "PV19"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 0, 0],
    },
    {
        code: 11,
        en_name: "Carmine",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PR83"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 1, 1],
    },
    {
        code: 12,
        en_name: "Rose Madder",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PR83"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 13,
        en_name: "Opera (Quinacridone Opera)",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 1,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["BV10", "PR122"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 1, 1, 1],
    },
    {
        code: 14,
        en_name: "Cadmium Red Light",
        fr_name: "",
        jp_name: "",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PO20", "PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 15,
        en_name: "Cadmium Red Deep",
        fr_name: "",
        jp_name: "",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 16,
        en_name: "Cadmium Red Orange",
        fr_name: "",
        jp_name: "",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PO20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 17,
        en_name: "Cadmium Red Purple",
        fr_name: "",
        jp_name: "",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 18,
        en_name: "Vermilion",
        fr_name: "",
        jp_name: "",
        series: "F",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PO20", "PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 19,
        en_name: "Vermilion Hue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PR254", "PY10"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 22,
        en_name: "Scarlet Lake",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PR254", "PV19"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 25,
        en_name: "Brilliant Pink",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PR209", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 26,
        en_name: "Shell Pink",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 27,
        en_name: "Quinacridone Scarlet",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: true,
        pigments: ["PR209"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    // Yellow
    {
        code: 30,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 31,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 32,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 33,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 34,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 35,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 36,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 37,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 38,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 39,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 40,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 41,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 42,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 43,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 44,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 46,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 47,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 48,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 49,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 50,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 51,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // GREEN
    {
        code: 60,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 61,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 62,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 63,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 64,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 65,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 66,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 67,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 69,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 70,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 71,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 74,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 75,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 77,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 78,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 79,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // BLUE
    {
        code: 90,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 91,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 92,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 93,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 94,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 95,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 96,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 97,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 98,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 99,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 101,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 102,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 103,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 104,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 105,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 106,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 107,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 108,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // VIOLET
    {
        code: 110,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 112,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 113,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 115,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 116,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 117,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 119,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 120,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 170,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 175,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // BROWN & BLACK
    {
        code: 129,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 130,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 131,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 132,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 133,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 134,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 135,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 136,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 139,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 141,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 142,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 137,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 138,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 140,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // GREY & WHITE
    {
        code: 151,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 152,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 153,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 155,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 156,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 157,
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 2, // W002 but W201 not 202
        en_name: "",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 3,
        en_name: "Titanium White (Opaque White)",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PW6"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    // GOLD & SILVER
    {
        code: 190,
        en_name: "Gold",
        fr_name: "",
        jp_name: "ゴールド",
        series: "C",
        perm: 4,
        opacity: 2,
        staining: 0,
        granulation: true,
        pigments: ["PW20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 191,
        en_name: "Silver",
        fr_name: "",
        jp_name: "シルバー",
        series: "C",
        perm: 4,
        opacity: 2,
        staining: 0,
        granulation: true,
        pigments: ["PW20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
];
