export interface Paint {
    code: number;
    en_name: string;
    fr_name: string;
    jp_name: string;
    series: "A" | "B" | "C" | "D" | "E" | "F";
    perm: 0 | 1 | 2 | 3 | 4;
    opacity: 0 | 1 | 2 | 3;
    staining: 0 | 1 | 2;
    granulation: boolean;
    pigments: string[];
    size: [number, number, number]; // 5ml 15ml 60ml
    sets: [number, number, number, number, number, number, number, number];
}

export const paintFilters = [
    "Permanence",
    "Opacity",
    "Staining",
    "Granulating",
    "Series",
    "Family",
    "Sets",
    "Size",
];

export const paintSymbols = {
    opacity: ["◯", "⦶", "◐", "⬤"],
    staining: ["☐", "◩", "◼"],
};

export const paintFamily = {
    red: [
        5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 25, 26, 27,
    ],
    yellow: [
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48,
        49, 50, 51,
    ],
    green: [60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 74, 75, 77, 78, 79],
    blue: [
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 102, 103, 104, 105, 106,
        107, 108,
    ],
    violet: [110, 112, 113, 115, 116, 117, 119, 120, 170, 175],
    brown_black: [
        129, 130, 131, 132, 133, 134, 135, 136, 139, 141, 142, 137, 138, 140,
    ],
    grey_white: [151, 152, 153, 155, 156, 157, 2, 3],
    gold_silver: [190, 191],
};

export const hbPaints: Paint[] = [
    // RED
    {
        code: 5,
        en_name: "Quinacridone Red",
        fr_name: "Rouge Quinacridone",
        jp_name: "キナクリドン　レッド",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PV19"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 6,
        en_name: "Pyrrole Rubin",
        fr_name: "",
        jp_name: "ピロール　ルビン",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR264"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 7,
        en_name: "Pyrrole Red",
        fr_name: "Rouge Pyrrol",
        jp_name: "ビロール　レッド",
        series: "A",
        perm: 3,
        opacity: 2,
        staining: 2,
        granulation: false,
        pigments: ["PR254"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 8,
        en_name: "Perylene Maroon",
        fr_name: "Marron Pérylène",
        jp_name: "ベリレン　マルーン",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PR179"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 9,
        en_name: "Permanent Alizarin Crimson",
        fr_name: "Permanent Alizarine Cramoisie",
        jp_name: "パーマネント　アリザリン　クリムソン",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PV19", "PBr25"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 10,
        en_name: "Crimson Lake",
        fr_name: "Laque Cramoisie",
        jp_name: "クリムソン　レーキ",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PR177", "PR122", "PV19"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 0, 0],
    },
    {
        code: 11,
        en_name: "Carmine",
        fr_name: "Carmin",
        jp_name: "カーマイン",
        series: "A",
        perm: 2,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PR83"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 1, 1],
    },
    {
        code: 12,
        en_name: "Rose Madder",
        fr_name: "Laque de Garance Rose",
        jp_name: "ローズ　マダー",
        series: "A",
        perm: 2,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PR83"],
        size: [1, 1, 1],
        sets: [0, 0, 1, 1, 0, 1, 0, 0],
    },
    {
        code: 13,
        en_name: "Opera (Quinacridone Opera)",
        fr_name: "Opéra (Opéra Quinacridone)",
        jp_name: "オペラ　(キナクリドン　オペラ)",
        series: "B",
        perm: 1,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["BV10", "PR122"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 1, 1, 1],
    },
    {
        code: 14,
        en_name: "Cadmium Red Light",
        fr_name: "Rouge de Cadmium Clair",
        jp_name: "カドミウム　レッド　ライト",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PO20", "PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 15,
        en_name: "Cadmium Red Deep",
        fr_name: "Rouge de Cadmium Foncé",
        jp_name: "カドミウム　レッド　ディープ",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 16,
        en_name: "Cadmium Red Orange",
        fr_name: "Rouge de Cadmium Orangé",
        jp_name: "カドミウム　レッド　オレンジ",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PO20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 17,
        en_name: "Cadmium Red Purple",
        fr_name: "Rouge de Cadmium Pourpre",
        jp_name: "カドミウム　レッド　パープル",
        series: "E",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 18,
        en_name: "Vermilion",
        fr_name: "Vermillon",
        jp_name: "パーミリオン",
        series: "F",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PO20", "PR108"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 19,
        en_name: "Vermilion Hue",
        fr_name: "Vermillon Imit.",
        jp_name: "パーミリオン　ヒュー",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PR254", "PY110"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 22,
        en_name: "Scarlet Lake",
        fr_name: "Laque Écarlate",
        jp_name: "スカーレット　レーキ",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PR254", "PV19"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 25,
        en_name: "Brilliant Pink",
        fr_name: "Rose Brillant",
        jp_name: "ブリリアント　ピンク",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PR209", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 26,
        en_name: "Shell Pink",
        fr_name: "Rose de Coquille",
        jp_name: "シェル　ピンク",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 27,
        en_name: "Quinacridone Scarlet",
        fr_name: "Écarlate Quinacridone",
        jp_name: "キナクリドン　スカーレット",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: true,
        pigments: ["PR209"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    // Yellow
    {
        code: 30,
        en_name: "Naples Yellow",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 0,
        granulation: false,
        pigments: ["PY35", "PY42", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 31,
        en_name: "Jaune Brilliant No. 1",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 0,
        granulation: false,
        pigments: ["PO20", "PY35", "PW6"],
        size: [1, 1, 1],
        sets: [0, 1, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 32,
        en_name: "Jaune Brilliant No. 2",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PO20", "PW6"],
        size: [1, 1, 0],
        sets: [0, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 33,
        en_name: "Lemon Yellow",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 0,
        granulation: false,
        pigments: ["PY3", "PY184"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 1, 1, 1],
    },
    {
        code: 34,
        en_name: "Yellow Ochre",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PY42"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 35,
        en_name: "Permanent Yellow Lemon",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PY3", "PY74"],
        size: [1, 1, 1],
        sets: [0, 0, 1, 1, 0, 0, 0, 0],
    },
    {
        code: 36,
        en_name: "Permanent Yellow Light",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PY74", "PY83"],
        size: [1, 1, 0],
        sets: [1, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 37,
        en_name: "Permanent Yellow Deep",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PY74", "PY83"],
        size: [1, 1, 1],
        sets: [0, 0, 1, 1, 0, 1, 0, 1],
    },
    {
        code: 38,
        en_name: "Permanent Yellow Orange",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PY74", "PY83", "PO73"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 39,
        en_name: "Aureolin",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 3,
        opacity: 0,
        staining: 0,
        granulation: false,
        pigments: ["PY154", "PY175", "PY150"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 1, 0, 1],
    },
    {
        code: 40,
        en_name: "Cadmium Yellow Lemon",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PY35"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 41,
        en_name: "Cadmium Yellow Pale",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PY35"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 42,
        en_name: "Cadmium Yellow Light",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PY35"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 43,
        en_name: "Cadmium Yellow Deep",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PO20", "PY35"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 44,
        en_name: "Cadmium Yellow Orange",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PO20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 46,
        en_name: "Greenish Yellow",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PY150", "PG7", "PBr25"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 47,
        en_name: "Brilliant Orange",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PO73", "PY110"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 48,
        en_name: "Gamboge Nova",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 0,
        granulation: false,
        pigments: ["PY154", "PY150", "PY110"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 49,
        en_name: "Isoindolinone Yellow Deep",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PY110"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 50,
        en_name: "Imidazolone Yellow",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 0,
        granulation: false,
        pigments: ["PY154"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 51,
        en_name: "Imidazolone Lemon",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 0,
        granulation: false,
        pigments: ["PY175"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // GREEN
    {
        code: 60,
        en_name: "Viridian",
        fr_name: "",
        jp_name: "",
        series: "E",
        perm: 4,
        opacity: 0,
        staining: 1,
        granulation: true,
        pigments: ["PG18"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 61,
        en_name: "Viridian Hue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PG7"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 62,
        en_name: "Hooker's Green",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PG7", "PY110", "PY150"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 0, 1],
    },
    {
        code: 63,
        en_name: "Cobalt Green",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 3,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PG18", "PB28", "PW6"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 1, 0, 1, 1, 1],
    },
    {
        code: 64,
        en_name: "Emerald Green Nova",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PY3", "PG7", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 1, 1, 1],
    },
    {
        code: 65,
        en_name: "Terre Verte",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PG23", "PG17"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 1, 0, 1, 1, 1],
    },
    {
        code: 66,
        en_name: "Permanent Green No. 1",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PY3", "PY53", "PG7"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 67,
        en_name: "Permanent Green No. 2",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PY74", "PY53", "PG7"],
        size: [1, 1, 0],
        sets: [0, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 69,
        en_name: "Cadmium Green Pale",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PY35", "PG18"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 70,
        en_name: "Cadmium Green Deep",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PY35", "PG7", "PG16"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 71,
        en_name: "Compose Green",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 3,
        staining: 0,
        granulation: false,
        pigments: ["PY3", "PG7", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 74,
        en_name: "Olive Green",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["PY150", "PG7", "PBr25"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 1, 1, 1],
    },
    {
        code: 75,
        en_name: "Sap Green",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PY150", "PG7", "PR122"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 1, 1, 1],
    },
    {
        code: 77,
        en_name: "Leaf Green",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 0,
        granulation: false,
        pigments: ["PY154", "PG7"],
        size: [1, 1, 1],
        sets: [0, 1, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 78,
        en_name: "Bamboo Green",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PG36"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 79,
        en_name: "Shadow Green",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PBk31"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    // BLUE
    {
        code: 90,
        en_name: "Cobalt Blue",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 4,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["PB28"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 91,
        en_name: "Cobalt Blue Hue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PB28", "PB15"],
        size: [1, 1, 0],
        sets: [1, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 92,
        en_name: "Cerulean Blue",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 4,
        opacity: 2,
        staining: 1,
        granulation: true,
        pigments: ["PB35"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 1, 1, 1, 1, 1],
    },
    {
        code: 93,
        en_name: "Ultramarine Light",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["PB29"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 94,
        en_name: "Ultramarine Deep",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["PB29"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 1, 0, 1, 1, 1],
    },
    {
        code: 95,
        en_name: "Verditer Blue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PB28", "PW6"],
        size: [1, 1, 1],
        sets: [0, 1, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 96,
        en_name: "Compose Blue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PB15", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 1, 1, 0, 1, 0, 0],
    },
    {
        code: 97,
        en_name: "Prussian Blue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PB27"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 98,
        en_name: "Indigo",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 2,
        staining: 2,
        granulation: false,
        pigments: ["PB15", "PBk6", "PR122"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 99,
        en_name: "Turquoise Blue",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PG7", "PB15", "PW6"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 101,
        en_name: "Peacock Blue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: true,
        pigments: ["PG7", "PB15"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 102,
        en_name: "Marine Blue",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: false,
        pigments: ["PB16", "PG7"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 103,
        en_name: "Royal Blue",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PB60"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 104,
        en_name: "Horizon Blue",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PB15", "PG7", "PW6"],
        size: [1, 1, 1],
        sets: [0, 1, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 105,
        en_name: "Manganese Blue Nova",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PB15"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 106,
        en_name: "Cobalt Turquoise Light",
        fr_name: "",
        jp_name: "",
        series: "D",
        perm: 4,
        opacity: 2,
        staining: 1,
        granulation: true,
        pigments: ["PB28"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 107,
        en_name: "Phthalo Blue Yellow Shade",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PB15"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 108,
        en_name: "Phthalo Blue Red Shade",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 1,
        staining: 2,
        granulation: false,
        pigments: ["PB15"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // VIOLET
    {
        code: 110,
        en_name: "Cobalt Violet Light",
        fr_name: "",
        jp_name: "",
        series: "F",
        perm: 4,
        opacity: 1,
        staining: 0,
        granulation: true,
        pigments: ["PV47"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 1, 0, 0],
    },
    {
        code: 112,
        en_name: "Mineral Violet",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PB29", "PR122", "PBr25"],
        size: [1, 1, 0],
        sets: [0, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 113,
        en_name: "Mars Violet",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PR101", "PV23", "PBr7"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 115,
        en_name: "Permanent Violet",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PV23"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 1, 1],
    },
    {
        code: 116,
        en_name: "Lavendar",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PR15", "PB29", "PW6"],
        size: [1, 1, 1],
        sets: [0, 1, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 117,
        en_name: "Lilac",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 2,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PR122", "PV23", "PW6"],
        size: [1, 1, 0],
        sets: [0, 1, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 119,
        en_name: "Quinacridone Magenta",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PR122"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 120,
        en_name: "Quinacridone Violet",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PV19"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 1, 1],
    },
    {
        code: 170,
        en_name: "Bright Rose (Luminous)",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 1,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["BV11", "AB83"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 175,
        en_name: "Bright Violet (Luminous)",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 1,
        opacity: 1,
        staining: 1,
        granulation: true,
        pigments: ["BV7", "BV15"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    // BROWN & BLACK
    {
        code: 129,
        en_name: "Umber",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 2,
        granulation: false,
        pigments: ["PBr7"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 130,
        en_name: "Light Red",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 2,
        granulation: false,
        pigments: ["PR101"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 1, 0, 0, 0, 0],
    },
    {
        code: 131,
        en_name: "Raw Umber",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PBr7", "PY42"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 132,
        en_name: "Raw Sienna",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 1,
        staining: 1,
        granulation: false,
        pigments: ["PBr7", "PY42"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 133,
        en_name: "Burnt Umber",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PBr7"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 134,
        en_name: "Burnt Sienna",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 1,
        granulation: true,
        pigments: ["Pbr7"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 1, 1, 1, 1],
    },
    {
        code: 135,
        en_name: "Indian Red",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PR101"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 136,
        en_name: "Sepia",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PBr7", "PBk6"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 1, 1, 1],
    },
    {
        code: 139,
        en_name: "Vandyke Brown",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 0,
        staining: 2,
        granulation: true,
        pigments: ["PY110", "PBr7", "PBk9"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 0, 0],
    },
    {
        code: 141,
        en_name: "Imidazolone Brown",
        fr_name: "",
        jp_name: "",
        series: "B",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PBr25"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 142,
        en_name: "Quinacridone Gold",
        fr_name: "",
        jp_name: "",
        series: "C",
        perm: 3,
        opacity: 0,
        staining: 1,
        granulation: false,
        pigments: ["PO48", "PY150"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 137,
        en_name: "Peach Black",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: true,
        pigments: ["PBk1"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 138,
        en_name: "Ivory Black",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 2,
        staining: 2,
        granulation: true,
        pigments: ["PBk9"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 140,
        en_name: "Lamp Black",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PBk6"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    // GREY & WHITE
    {
        code: 151,
        en_name: "Yellow Grey",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PY42", "PBk6", "PW6"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 1, 0, 0, 1, 1],
    },
    {
        code: 152,
        en_name: "Green Grey",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PG17", "PG23", "PBk6"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 153,
        en_name: "Grey of Grey",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 0,
        granulation: false,
        pigments: ["PBk6", "PW6"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 1, 1, 1],
    },
    {
        code: 155,
        en_name: "Davy's Grey",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 2,
        staining: 1,
        granulation: false,
        pigments: ["PBr7", "PBk6", "PW6"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    {
        code: 156,
        en_name: "Payne's Grey",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PBk6", "PB15", "PR122"],
        size: [1, 1, 1],
        sets: [0, 0, 0, 0, 1, 0, 1, 1],
    },
    {
        code: 157,
        en_name: "Neutral Tint",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 3,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PBk6", "PB15", "PV19"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 0],
    },
    {
        code: 2, // W002 but W201 not 202
        en_name: "Chinese White",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 1,
        granulation: false,
        pigments: ["PW6"],
        size: [1, 1, 1],
        sets: [1, 0, 1, 1, 0, 1, 1, 1],
    },
    {
        code: 3,
        en_name: "Titanium White (Opaque White)",
        fr_name: "",
        jp_name: "",
        series: "A",
        perm: 4,
        opacity: 3,
        staining: 2,
        granulation: false,
        pigments: ["PW6"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 0, 1],
    },
    // GOLD & SILVER
    {
        code: 190,
        en_name: "Gold",
        fr_name: "",
        jp_name: "ゴールド",
        series: "C",
        perm: 4,
        opacity: 2,
        staining: 0,
        granulation: true,
        pigments: ["PW20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
    {
        code: 191,
        en_name: "Silver",
        fr_name: "Argent",
        jp_name: "シルバー",
        series: "C",
        perm: 4,
        opacity: 2,
        staining: 0,
        granulation: true,
        pigments: ["PW20"],
        size: [1, 1, 0],
        sets: [0, 0, 0, 0, 0, 0, 1, 1],
    },
];
